(()=>{const C=window.NAHODKA||{};if(!C.url||!C.key||!window.supabase)return;
const sb=supabase.createClient(C.url,C.key);S.backend=true;S.items=[];S.chats={};S.peers={};S.uid=null;S.auth=0;S.pw="";
S.favs=new Set(ld("nd_favs")||[]);document.head.insertAdjacentHTML("beforeend","<style>.bd{display:none!important}</style>");
const AT=o=>Object.keys(o).sort((a,b)=>b.length-a.length).reverse().forEach(k=>{P[k]=o[k];RX.unshift([new RegExp("(?<![\\u0400-\\u04FF])"+k.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")+"(?![\\u0400-\\u04FF])","g"),o[k]])});
AT({"Введите email":"Enter your email","Пароль":"Password","Пароль: минимум 6 символов":"Password: at least 6 characters","минимум 6 символов":"at least 6 characters","Подтвердите email по письму и войдите":"Confirm your email via the message, then log in","Неверный email или пароль":"Wrong email or password","Не отправлено":"Not sent","Не удалось опубликовать":"Could not publish","Ошибка":"Error","Чат":"Chat","Пока нет объявлений. Станьте первым!":"No listings yet. Be the first!","Сообщений пока нет. Откройте объявление и нажмите «Написать».":"No messages yet. Open a listing and tap “Message”."});
const CE=Object.fromEntries(CATS.map(c=>[c[0],c[1]])),ago=t=>{const h=Math.floor((Date.now()-new Date(t))/36e5);if(h<1)return"только что";if(h<24)return h+" ч. назад";const d=Math.floor(h/24);return d+(d==1?" день назад":d<5?" дня назад":" дней назад")};
const mapL=r=>{const p=r.profiles||{},ph=r.photos||[];S.peers[r.user_id]={name:p.name||"—",av:p.avatar_url};return{id:r.id,t:r.title,sh:r.title,p:+r.price,e:CE[r.category]||"🛍️",cat:r.category,a:r.area,c:r.condition,pill:r.condition,pc:"g",s:r.condition,ds:r.description||"",d:r.description||"Без описания",n:ph.length||1,src:ph[0],u:p.name||"—",uid:r.user_id,uav:p.avatar_url,utype:p.type,usince:p.created_at?new Date(p.created_at).getFullYear():"",ago:ago(r.created_at),mine:r.user_id==S.uid}};
const err=e=>toast(e&&e.message&&!/fetch/i.test(e.message)?e.message:"Ошибка");
async function up(path,du){const b=await(await fetch(du)).blob(),{error}=await sb.storage.from("photos").upload(path,b,{contentType:"image/jpeg",upsert:true});if(error)throw error;return sb.storage.from("photos").getPublicUrl(path).data.publicUrl}
async function loadL(){const{data}=await sb.from("listings").select("*,profiles(name,avatar_url,type,created_at)").order("created_at",{ascending:false}).limit(100);S.items=(data||[]).map(mapL)}
async function loadM(){const{data}=await sb.from("messages").select("*").order("created_at"),ch={},ids=new Set();(data||[]).forEach(m=>{const o=m.sender_id==S.uid?m.receiver_id:m.sender_id;(ch[o]=ch[o]||[]).push([m.sender_id==S.uid?"me":"them",m.body]);ids.add(o)});
const need=[...ids].filter(i=>!S.peers[i]);if(need.length){const{data:ps}=await sb.from("profiles").select("id,name,avatar_url").in("id",need);(ps||[]).forEach(p=>S.peers[p.id]={name:p.name,av:p.avatar_url})}
const c=JSON.stringify(ch)!=JSON.stringify(S.chats);S.chats=ch;return c}
async function boot(){const{data:{session}}=await sb.auth.getSession();if(!session){S.auth=0;S.me=null;S.uid=null;R();return}
S.uid=session.user.id;const u=session.user,{data:p}=await sb.from("profiles").select("*").eq("id",S.uid).maybeSingle();
S.me={name:p?p.name:u.email.split("@")[0],phone:(u.user_metadata||{}).phone||"",email:u.email,area:p?p.area:AREAS[0],bio:p&&p.bio||"",type:p?p.type:"Частное лицо",av:p&&p.avatar_url||"",since:new Date(p?p.created_at:u.created_at).getFullYear()};
await Promise.all([loadL(),loadM()]);S.auth=1;S.pre=null;S.stack=[];S.tab="home";R()}
saveAcc=async function(edit){const f=S.pf;if(f.name.trim().length<2)return toast("Введите имя");if(!edit&&!/^\S+@\S+\.\S+$/.test(f.email||""))return toast("Введите email");if(!edit&&(S.pw||"").length<6)return toast("Пароль: минимум 6 символов");
try{let uid=S.uid;if(!edit){const{data,error}=await sb.auth.signUp({email:f.email.trim(),password:S.pw,options:{data:{phone:f.phone.trim()}}});if(error)throw error;if(!data.session)return toast("Подтвердите email по письму и войдите");uid=data.user.id}
else await sb.auth.updateUser({data:{phone:f.phone.trim()}});
let av=f.av;if(av&&av.startsWith("data:"))av=await up(uid+"/avatar-"+Date.now()+".jpg",av);
const{error}=await sb.from("profiles").upsert({id:uid,name:f.name.trim(),area:f.area,bio:f.bio,type:f.type,avatar_url:av||null});if(error)throw error;
S.pw="";S.uid=uid;await boot();if(edit){S.tab="profile";R()}toast(edit?"Профиль сохранён":"Добро пожаловать!")}catch(e){err(e)}};
doLogin=async function(){try{const{error}=await sb.auth.signInWithPassword({email:(S.le||"").trim(),password:S.lp2||""});if(error)return toast("Неверный email или пароль");await boot();toast("Добро пожаловать!")}catch(e){err(e)}};
logout=async function(){await sb.auth.signOut();S.auth=0;S.pre=null;S.stack=[];S.tab="home";S.me=null;S.uid=null;R()};
delAcc=async function(){if(!confirm(S.lang=="en"?"Delete your profile and all your listings?":"Удалить профиль и все ваши объявления?"))return;await sb.from("listings").delete().eq("user_id",S.uid);await sb.from("profiles").delete().eq("id",S.uid);await logout()};
delIt=async function(id){await sb.from("listings").delete().eq("id",id);await loadL();toast("Объявление удалено")};
pub=async function(){const f=S.fm,p=+f.p;if(!f.n.trim()||!p)return toast("Укажите название и цену");
try{const ph=[];for(let k=0;k<S.ph.length;k++)ph.push(await up(S.uid+"/"+Date.now()+"-"+k+".jpg",S.ph[k]));
const{error}=await sb.from("listings").insert({user_id:S.uid,title:f.n.trim(),price:p,category:f.c,area:f.a,condition:f.cond,description:f.d,torg:!!f.torg,photos:ph});if(error)throw error;
await loadL();S.ph=[];S.fm=FM();S.tab="home";S.stack=[];R();toast("Опубликовано")}catch(e){toast("Не удалось опубликовать")}};
const fv0=fav;fav=function(id){fv0(id);try{localStorage.setItem("nd_favs",JSON.stringify([...S.favs]))}catch(e){}};
openChat=uid=>{S.chats[uid]=S.chats[uid]||[];go("chat",uid)};
const avh=(a,n)=>a?`<img class="ic" style="width:46px;height:46px;object-fit:cover" src="${a}" alt="">`:`<div class="av" style="font-weight:800;color:#a2611c">${esc((n||"?")[0].toUpperCase())}</div>`;
V.chats=()=>{const ks=Object.keys(S.chats);return `<main><div class="h1" style="justify-content:center;margin-top:4px">Чаты</div>${ks.map(u=>{const p=S.peers[u]||{name:"—"},l=(S.chats[u].slice(-1)[0]||["",""])[1];return`<div class="row" onclick="go('chat','${u}')">${avh(p.av,p.name)}<div style="flex:1;min-width:0"><b>${esc(p.name)}</b><div class="mu" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(l)}</div></div></div>`}).join("")||'<p class="mu" style="text-align:center;margin-top:40px">Сообщений пока нет. Откройте объявление и нажмите «Написать».</p>'}</main>`};
V.chat=u=>head((S.peers[u]||{name:"Чат"}).name)+`<main id="m" style="padding-top:8px">${(S.chats[u]||[]).map(x=>`<div class="msg ${x[0]=="me"?"me":""}">${esc(x[1])}</div>`).join("")}</main><div style="display:flex;gap:8px;padding:8px 12px;border-top:1px solid var(--ln)"><input id="mi" class="inp" placeholder="Сообщение" onkeydown="if(event.key=='Enter')send('${u}')"><button class="ib" aria-label="Отправить" onclick="send('${u}')">➤</button></div>`;
send=async function(u){const i=$("#mi"),v=i.value.trim();if(!v)return;(S.chats[u]=S.chats[u]||[]).push(["me",v]);R();const{error}=await sb.from("messages").insert({sender_id:S.uid,receiver_id:u,body:v});if(error)toast("Не отправлено")};
const it1=V.item;V.item=id=>{let h=it1(id);const i=S.items.find(x=>x.id==id);if(i&&!i.mine&&i.uid){h=h.replace('<div class="av" style="width:64px;height:64px">👤</div>',i.uav?`<img src="${i.uav}" class="ic" style="width:64px;height:64px;object-fit:cover" alt="">`:`<div class="av" style="width:64px;height:64px;font-weight:800;color:#a2611c">${esc((i.u||"?")[0].toUpperCase())}</div>`).replace('Частное лицо',i.utype||"Частное лицо").replace(/<span style="color:#f0a020">★★★★★<\/span> 5\.0 \(32 отзыва\)/,"Новый пользователь").replace('с 2024','с '+i.usince).replace(/onclick="go\('chat','[^']*'\)"/,`onclick="openChat('${i.uid}')"`)}return h};
const hm1=V.home;V.home=()=>hm1().replace('<div class="g3"></div>','<p class="mu" style="text-align:center;padding:30px 0">Пока нет объявлений. Станьте первым!</p>');
const rg1=V.reg;V.reg=()=>rg1().replace('<span class="mu" style="font-weight:400">Необязательно</span>','<i class="rq">*</i>').replace('<button class="btn" onclick="saveAcc(false)">','<div class="fc"><b><span>Пароль <i class="rq">*</i></span><span class="mu" style="font-weight:400">минимум 6 символов</span></b><input class="inp" type="password" autocomplete="new-password" value="" oninput="S.pw=this.value"></div><button class="btn" onclick="saveAcc(false)">');
V.login=()=>`<main><button class="ib" aria-label="Назад" onclick="S.pre=null;R()">‹</button><img class="lg2" src="${IMG.logo}" alt="Находка Dubai"><h2 style="text-align:center;font-size:24px;margin-top:6px">Вход</h2><div class="fc" style="margin-top:14px"><b><span>Email</span></b><input class="inp" type="email" autocomplete="username" value="${esc(S.le||"")}" oninput="S.le=this.value"></div><div class="fc"><b><span>Пароль</span></b><input class="inp" type="password" autocomplete="current-password" oninput="S.lp2=this.value" onkeydown="if(event.key=='Enter')doLogin()"></div><button class="btn" onclick="doLogin()">Войти</button><button class="lk" onclick="S.pf=PF();S.pre='reg';R()">Нет аккаунта? Создать</button></main>`;
setInterval(async()=>{if(!S.uid||!S.auth)return;try{const t=S.stack[S.stack.length-1],v=$("#mi")&&$("#mi").value;if(await loadM()&&((t&&t[0]=="chat")||(!t&&S.tab=="chats"))){R();if(v&&$("#mi")){$("#mi").value=v;$("#mi").focus()}}}catch(e){}},5000);
sb.auth.onAuthStateChange((ev)=>{if(ev=="SIGNED_OUT"&&S.auth){S.auth=0;R()}});
R();boot();})();
